
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/toy_project_clone
    username: root
    password: mariadb
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
        show_sql: true

server:
  port: 9003

logging:
  level:
    com.spring.toyproject: DEBUG
    # SQL ??
    org.hibernate.SQL: DEBUG
    # ?? ???? ????
    org.springframework.web: DEBUG
    # SQL ???? ??? ??
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Jwt setting
jwt:
  # secret key (실제 운영에서는 환경 변수로 관리)
  secret: buVK/wwcaaV+G9bCkr+UurhrDd5qScHC6zaBX/pcDuc=
  # 만료시간 (밀리초) - 24시간
  expiration: 86400000